# permissions for end users to edit mystatefulsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: devops-golang-test
    app.kubernetes.io/managed-by: kustomize
  name: mystatefulset-editor-role
rules:
- apiGroups:
  - apps.my.com
  resources:
  - mystatefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.my.com
  resources:
  - mystatefulsets/status
  verbs:
  - get
